---
<<<<<<< HEAD
# defaults file for nginx
=======
# defaults file for nginx
  command: > 
     aws rds describe-db-cluster-endpoints \
       --db-cluster-identifier daviddb
  register: rds_endpoint

  debug:
    msg: "{{ rds_endpoint.stdout | from_json | json_query('Endpoint[0]')}}" 
>>>>>>> 5858f4efef95e909950575655fd68bcc6d00e1ed
